model:
    name: original
    forecast_lead: 1
data:
    predictors:
    - channel_0013_brightness_temperature
    - channel_0003_scaled_radiance
    - channel_0015_brightness_temperature
    - hus850
    - huss
    - hus500
    - tas
    - ta850
    - hus700
    - psl
    - channel_0009_brightness_temperature
    - ta700
    - solar_elevation
    - ta500
    - channel_0005_scaled_radiance
    target: cloud_optical_depth
    