model:
    name: b-mod
    forecast_lead: 3
    parameters:
        random_state: 42
        n_estimators: 2000
        early_stopping_rounds: 50
        learning_rate: 0.01
        eval_metric: rmse
data:
    predictors:
        - hus500
        - ta500
        - KI
        - RH24mean
        - TCD
        - ATP
        - psl
        - delta_huss
        - delta_hus850
        - delta_hus700
        - delta_hus500
        - delta_tas
        - delta_ta850
        - delta_ta700
        - delta_ta500
        - delta_KI
        - delta_RH24mean
        - delta_TCD
        - delta_psl
        - delta_csi
    target: csi
