model:
    name: b-rad
    forecast_lead: 3
    parameters:
        random_state: 42
        n_estimators: 2000
        early_stopping_rounds: 50
        learning_rate: 0.035
        eval_metric: rmse
        max_depth: 4
        min_child_weight: 3
        subsample: 0.774
        'colsample_bytree': 0.714620690738731
        gamma: 0.00888
        reg_alpha: 0.03242
        reg_lambda: 0.376
data:
    predictors:
        - channel_0003_scaled_radiance
        - channel_0005_scaled_radiance
        - channel_0007_brightness_temperature
        - channel_0009_brightness_temperature
        - channel_0015_brightness_temperature
        - channel_0007_0013_difference
        - channel_0011_0013_difference
        - channel_0013_0015_difference
        - cloud_optical_depth
        - delta_channel_0003_scaled_radiance
        - delta_channel_0005_scaled_radiance
        - delta_channel_0007_brightness_temperature
        - delta_channel_0009_brightness_temperature
        - delta_channel_0015_brightness_temperature
        - delta_channel_0007_0013_difference
        - delta_channel_0011_0013_difference
        - delta_channel_0013_0015_difference
        - delta_csi
        - delta_cloud_optical_depth
    target: csi
