model:
    name: b-rad
    forecast_lead: 2
    parameters:
        random_state: 42
        n_estimators: 2000
        early_stopping_rounds: 50
        learning_rate: 0.03
        eval_metric: rmse
data:
    predictors:
        - channel_0003_scaled_radiance
        - channel_0015_brightness_temperature
        - channel_0007_0013_difference
        - channel_0011_0013_difference
        - csi
        - delta_channel_0003_scaled_radiance
        - delta_channel_0015_brightness_temperature
        - delta_channel_0007_0013_difference
        - delta_channel_0011_0013_difference
        - delta_csi
    target: csi
