model:
    name: base
    forecast_lead: 3
    parameters:
        random_state: 42
        n_estimators: 2000
        early_stopping_rounds: 50
        learning_rate: 0.035
        eval_metric: rmse
        max_depth: 4
        min_child_weight: 3
        subsample: 0.774
        'colsample_bytree': 0.714620690738731
        gamma: 0.00888
        reg_alpha: 0.03242
        reg_lambda: 0.376
data:
    predictors:
        - csi
        - delta_csi
    target: csi
