model:
    name: vanilla
    forecast_lead: 2
data:
    predictors:
    - channel_0013_brightness_temperature
    - channel_0003_scaled_radiance
    - channel_0015_brightness_temperature
    - hus850
    - hus500
    - ta850
    - hus700
    - ta700
    - ta500
    - channel_0013_0015_difference
    - channel_0011_0013_difference
    - channel_0007_0013_difference
    - KI
    - RH24mean
    - TCD
    - cloud_optical_depth
    target: cloud_optical_depth
    