#!/bin/bash 
#PBS -l walltime=1:00:00 
#PBS -l mem=96GB 
#PBS -l ncpus=48 
#PBS -l jobfs=10GB 
#PBS -l storage=gdata/dk92+gdata/rt52+scratch/nf33+gdata/rv74+gdata/rq0+gdata/ra22+gdata/xp65+gdata/er8+scratch/er8
#PBS -l other=hyperthread 
#PBS -q normal 
#PBS -P er8 
#PBS -o /home/548/cd3022/repos/solar-nowcast/logs/job_log.oe 
#PBS -j oe 

cd /home/548/cd3022/repos/solar-nowcast

source ./env.sh

python3 mouse/prepare_radiances.py 2025-01-01 5